bookingservice:
  image: blace/bookingservice:latest
  ports:
      - "9000:9000"
  container_name: "bookingservice"
  links:
     - mongodb
mongodb:
  image: mongo:latest
  volumes:
      - "/opt/mongodb:/data/db"
  ports:
    - "27017:27017"
  container_name: "mongodb"